name: "Ubuntu | GCC 12 | x64 | Debug "

on:
  push:
    branches: [ "master" ]
    paths:
      - include/**
      - test/**
      - .github/workflows/build_and_test_ubuntu_gcc12_x64_debug.yml
      - CMakeLists.txt
  pull_request:
    branches: [ "master" ]
    paths:
      - include/**
      - test/**
      - .github/workflows/build_and_test_ubuntu_gcc12_x64_debug.yml
      - CMakeLists.txt

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: turtlebrowser/get-conan@v1.2
        with:
          version: 1.59.0

      - name: Install GCC12
        shell: bash
        run:  |
          sudo apt update
          sudo apt install gcc-12 g++-12
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 120 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
          
      - name: Resolve dependencies
        run: |
          conan profile new default --detect
          conan install . -s build_type=${{env.BUILD_TYPE}} -s compiler.libcxx=libstdc++11 --install-folder=${{github.workspace}}/build/gcc/x64/debug --build=missing

      - name: Configure
        run: cmake -B ${{github.workspace}}/build/gcc/x64/debug -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build/gcc/x64/debug --config ${{env.BUILD_TYPE}} --target all

      - name: Test
        working-directory: ${{github.workspace}}/build/gcc/x64/debug/test
        run: ./proj_nameTest
