name: "Ubuntu | GCC 12 | x64 | Debug "

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build source package
        run: python setup.py sdist

      - name: Test
        run: |
          pip install ./dist/cppstart-?.?.?.tar.gz
          cppstart foo -c "some user"
          cd cppstart
          ./init.sh
          ./build.sh
