name: "Build & test"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: turtlebrowser/get-conan@v1.2
        with:
          version: 1.59.0
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 12
          platform: x64
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install build dependencies
        run: python3 -m pip install -U setuptools wheel appdirs gitpython
      - name: Build package
        run: python3 setup.py sdist
      - name: Test
        run: |
          pip install ./dist/cppstart-?.?.?.tar.gz
          cppstart foo -c "some user"
          cd foo
          conan profile new default --detect
          chmod +x init.sh
          chmod +x build.sh
          ./init.sh
          ./build.sh
