name: "Build & test"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: turtlebrowser/get-conan@v1.2
        with:
          version: 1.59.0
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 12
          platform: x64

      - name: Build source package
        run: python setup.py sdist

      - name: Test
        run: |
          pip install ./dist/cppstart-?.?.?.tar.gz
          cppstart foo -c "some user"
          cd foo
          conan profile new default --detect
          chmod +x init.sh
          chmod +x build.sh
          ./init.sh
          ./build.sh
