name: "Ubuntu | GCC 12 | x64 | Debug "

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: turtlebrowser/get-conan@v1.2
        with:
          version: 1.59.0

      - name: Build source package
        run: python setup.py sdist

      - name: Install GCC12
        shell: bash
        run:  |
          sudo apt update
          sudo apt install gcc-12 g++-12
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 120 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12

      - name: Resolve dependencies
        run: |
          conan profile new default --detect

      - name: Test
        run: |
          pip install ./dist/cppstart-?.?.?.tar.gz
          cppstart foo -c "some user"
          cd foo
          chmod +x init.sh
          chmod +x build.sh
          ./init.sh
          ./build.sh
