name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create version number
        run: |
          echo "number = '${GITHUB_REF#refs/*/}'" | sed 's/v//' > packaging/version.py
          cat packaging/version.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip' # caching pip dependencies
        run: python3 -m pip install -U setuptools wheel appdirs gitpython

      - name: Build package
        run: python3 setup.py sdist

      - name: Add packaged source code to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: dist/cppstart-*.*.*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true